# -*- coding: utf-8 -*-
"""praktium 3 Nikolas  G.211.25.0051.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bKkdVvQYagptiavB8eT5zMpe6HvWooO0
"""

import heapq

def shortest_path(graph, start_node):
    # Inisialisasi jarak semua node ke tak terhingga
    distances = {node: float('inf') for node in graph}
    distances[start_node] = 0

    # Priority Queue untuk menyimpan (jarak, node)
    pq = [(0, start_node)]

    while pq:
        current_distance, u = heapq.heappop(pq)

        # Jika jarak di PQ lebih besar dari yang tersimpan, abaikan
        if current_distance > distances[u]:
            continue

        # Cek tetangga dari node u
        for neighbor, weight in graph[u].items():
            distance = current_distance + weight

            # Jika ditemukan jalur yang lebih pendek ke tetangga
            if distance < distances[neighbor]:
                distances[neighbor] = distance
                heapq.heappush(pq, (distance, neighbor))

    return distances

# Contoh Graf (Representasi Adjacency List)
# Format: { node: { tetangga: bobot } }
graph = {
    'A': {'B': 4, 'C': 2},
    'B': {'A': 4, 'C': 5, 'D': 10},
    'C': {'A': 2, 'B': 5, 'D': 3},
    'D': {'B': 10, 'C': 3}
}

# Contoh penggunaan
hasil = shortest_path(graph, 'A')
print(f"Jarak terpendek dari A: {hasil}")
# Output: {'A': 0, 'B': 4, 'C': 2, 'D': 5}