# -*- coding: utf-8 -*-
"""tugas praktikum 2  b1 nikolas  G,211.25.0051

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_e5X6eMPrLro_KlFM0RL2bQFQ3KhX-I1
"""

class Node:
    def __init__(self, data):
        self.data, self.color = data, 1 # 1:Red, 0:Black
        self.parent, self.left, self.right = None, None, None

class RedBlackTree:
    def __init__(self):
        self.TNULL = Node(0); self.TNULL.color = 0
        self.root = self.TNULL

    def insert(self, key):
        node = Node(key); node.left = node.right = self.TNULL
        y = None; x = self.root
        while x != self.TNULL:
            y = x
            if node.data < x.data: x = x.left
            else: x = x.right
        node.parent = y
        if y == None: self.root = node
        elif node.data < y.data: y.left = node
        else: y.right = node
        if node.parent == None or node.parent.parent == None: return
        self.fix_insert(node)

    def fix_insert(self, k):
        while k.parent.color == 1:
            if k.parent == k.parent.parent.right:
                u = k.parent.parent.left
                if u.color == 1: u.color = k.parent.color = 0; k.parent.parent.color = 1; k = k.parent.parent
                else:
                    if k == k.parent.left: k = k.parent; self.right_rotate(k)
                    k.parent.color = 0; k.parent.parent.color = 1; self.left_rotate(k.parent.parent)
            else:
                u = k.parent.parent.right
                if u.color == 1: u.color = k.parent.color = 0; k.parent.parent.color = 1; k = k.parent.parent
                else:
                    if k == k.parent.right: k = k.parent; self.left_rotate(k)
                    k.parent.color = 0; k.parent.parent.color = 1; self.right_rotate(k.parent.parent)
            if k == self.root: break
        self.root.color = 0

    # Metode left_rotate dan right_rotate standar...
    def left_rotate(self, x):
        y = x.right; x.right = y.left
        if y.left != self.TNULL: y.left.parent = x
        y.parent = x.parent
        if x.parent == None: self.root = y
        elif x == x.parent.left: x.parent.left = y
        else: x.parent.right = y
        y.left = x; x.parent = y

    def right_rotate(self, y):
        x = y.left; y.left = x.right
        if x.right != self.TNULL: x.right.parent = y
        x.parent = y.parent
        if y.parent == None: self.root = x
        elif y == y.parent.right: y.parent.right = x
        else: y.parent.left = x
        x.right = y; y.left = x